### ISSUE TITLE
Running RamCloud client with java

### ISSUE THREAD

**Issue by MheniMerz** [PlatformLab/RAMCloud#20]
hi all,
i have a running RamCloud instance on one node,
im trying to start a java client that can read and write data, i've been following [these instructions](https://github.com/PlatformLab/RAMCloud/blob/master/bindings/java/README) to build and run the java client.
but when running `sudo ./gradlew run -Plocator=build/install/ramcloud/bin/ramcloud`
i get the following error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libramcloud_java759421568980880719.so: libramcloud.so: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at cz.adamh.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:116)
        at edu.stanford.ramcloud.Util.loadLibrary(Util.java:47)
        at edu.stanford.ramcloud.TestClient.<clinit>(TestClient.java:32)
:run FAILED

FAILURE: Build failed with an exception.
```
i tried running with the `debug` option and running `./runclient.sh` i basically get the same output.
seems like it's looking for a ramcloud library file, but maybe it's looking in the wrong place ?
any one had this before ?
thanks.
Mheni.

**Comment by MheniMerz** [comment]
add the path to `libramcloud.so` to the `LD_LIBRARY_PATH` environment variable
- add this line to your `.bashrc` file `export LD_LIBRARY_PATH=/home/antd/RAMCloud/obj.master` *in my case* that's where the file `libramcloud.so` is located
- then execute the same command to avoid rebooting the system `export LD_LIBRARY_PATH=/home/antd/RAMCloud/obj.master`
- you can now run `sudo ./gradlew run -Plocator=basic+udp:host=localhost,port=11100`
   * `Plocator` here is the service locator for the **coordinator** and not a path to a file

**Comment by centrys-sergiu** [comment]
This is not working for me unfortunately. 
The path to my libramcloud.so is `/home/ramdb/RAMCloud/obj.master/libramcloud.so`

Did all the steps described above by you. Here is the output of LD_LIBRARY_PATH: 
`ramdb@ramdb:~/RAMCloud/obj.master$ echo $LD_LIBRARY_PATH
/home/ramdb/RAMCloud/obj.master`

Here is the output while trying to run the client.
`ramdb@ramdb:~/RAMCloud/bindings/java$ sudo ./gradlew run -Plocator=basic+udp:host=ramdb,port=11100
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:javah UP-TO-DATE
:compileMainSharedLibraryMainCpp UP-TO-DATE
:linkMainSharedLibrary UP-TO-DATE
:mainSharedLibrary UP-TO-DATE
:copyLibs UP-TO-DATE
:jar UP-TO-DATE
:startScripts UP-TO-DATE
:installDist UP-TO-DATE
:make UP-TO-DATE
:run
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libramcloud_java6503341304544372223.so: libramcloud.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at cz.adamh.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:116)
	at edu.stanford.ramcloud.Util.loadLibrary(Util.java:47)
	at edu.stanford.ramcloud.TestClient.<clinit>(TestClient.java:32)
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

Any other suggestions would be much appreciated.

**Comment by jdellithorpe** [comment]
Hi @centrys-sergiu 

sudo doesn't preserve your environment variables (in particular, LD_LIBRARY_PATH). Can you run this without using sudo? I don't think sudo should be necessary to run this.

Best,
Jonathan

**Comment by centrys-sergiu** [comment]
You are right! However in order to run the client without sudo, I had to remove all the folders that were generated at build with sudo.

Thanks
